In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

arr_add = arr + 2
print("Addition:", arr_add)

arr_mul = arr * 2
print("Multiplication by 2:", arr_mul)


arr_div = arr / 2
print("Division:", arr_div)




Addition: [3 4 5 6 7]
Multiplication by 2: [ 2  4  6  8 10]
Division: [0.5 1.  1.5 2.  2.5]


In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
arr_reversed = arr[::-1]
print("Reversed array:", arr_reversed)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3, 3])

most_frequent_x = np.bincount(x).argmax()
most_frequent_y = np.bincount(y).argmax()

print("Most frequent value in x:", most_frequent_x)
print("Most frequent value in y:", most_frequent_y)

Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1
Most frequent value in y: 3


In [9]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Element at (1,2):", arr[0, 1])
print("Element at (3, 1):", arr[2, 0])


Element at (1,2): 20
Element at (3, 1): 70


In [12]:
name = "YourName"

arr = np.linspace(10, 100, 25)

print("Array:", arr)
print("Shape:", arr.shape)
print("Total Elements:", arr.size)
print("Data Type:", arr.dtype)
print("Total bytes consumed:", arr.nbytes)

transpose_arr = arr.reshape(-1, 1) 
print("Transposed using reshape:", transpose_arr)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total Elements: 25
Data Type: float64
Total bytes consumed: 200
Transposed using reshape: [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [20]:
ucs420_aman = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean: ", np.mean(ucs420_aman))
print("Median: ", np.median(ucs420_aman))
print("Max: ", np.max(ucs420_aman))
print("Min: ", np.min(ucs420_aman))
print("Unique elements: ", np.unique(ucs420_aman))

reshaped_ucs420 = ucs420_aman.reshape(4, 3)
print("Reshaped (4x3):", reshaped_ucs420)

resized_ucs420 = ucs420_aman.reshape(2, 6)  # 2x3 not possible
print("Resized (2x3):", resized_ucs420)

Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3): [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x3): [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
