In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a+2)


ModuleNotFoundError: No module named 'numpy'

In [2]:
print(a*3)

[ 3  6  9 12 15]


In [3]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [4]:
b=np.array([1,2,3,6,4,5])
r_array=b[::-1]
print(type(r_array))

<class 'numpy.ndarray'>


In [5]:
r_array=np.flip(b)
r_array

array([5, 4, 6, 3, 2, 1])

In [6]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.bincount(x)
print(y)
m=max(y)
print(m)
for i in range(len(y)):
    if(m==y[i]):
        print(i)

[0 5 2 1 1 1]
5
1


In [7]:
import numpy as np
y=np.array([1,1,1,2,3,4,2,4,3,3])
unique,counts=np.unique(y,return_counts=True)
most_frequent_value=unique[np.argmax(counts)]
indices=np.where(y==most_frequent_value)[0]
print("Most Frequent Value:",most_frequent_value)
print("Indices:",indices)

Most Frequent Value: 1
Indices: [0 1 2]


In [8]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[0])
print(arr[:,1])
print(arr[:,0])
print(arr[2])

20
[10 20 30]
[20 50 80]
[10 40 70]
[70 80 90]


In [9]:
print(arr[2][0])

70


In [10]:
Aman=np.linspace(10,100,25)
print(Aman)
print(np.ndim(Aman))
print(np.shape(Aman))
print(len(Aman))
print(Aman.dtype)
print(Aman.nbytes)
print(Aman.reshape(1,25))
print(Aman.T)
print(np.shape(Aman))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)


In [1]:
ucs420_Aman=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
m=np.mean(ucs420_Aman)
print("Mean:",m)
x=np.median(ucs420_Aman)
print("Median:",x)
y=np.max(ucs420_Aman)
print("Max:",y)
z=np.min(ucs420_Aman)
print("Min:",z)
reshaped_ucs420_Aman=ucs420_Aman.reshape(4,3)
print(reshaped_ucs420_Aman)
resized_ucs420_Aman=np.resize(reshaped_ucs420_Aman,(2,3))
print(resized_ucs420_Aman)

NameError: name 'np' is not defined